### ISSUE TITLE
如何处理list<T>呢？

### ISSUE THREAD

**Issue by staunchheart** [yaronzz/AIGCJson#1]
比如
class Student{
  ....
}
class xxx{
  public:
       string name;
       list<Student> students;
}
这种情况如何处理呢？
我测试报
AIGCJson.hpp:257:38: error: no match for 'operator[]' (operand types are 'std::__cxx11::list<Student>' and 'int')

**Comment by staunchheart** [comment]
我测试报这个错误
 no match for 'operator[]' (operand types are 'std::__cxx11::list<Student>' and 'int')

**Comment by yaronzz** [comment]
struct Student {
    double    id;
    bool    sex;
    double  score;
    std::string  name;

    AIGC_JSON_HELPER(id,sex,score,name)
};
struct Teacher {
    std::string name;
    int         subject;
    std::list<Student> stus;

    AIGC_JSON_HELPER(name, subject, stus)
};



yaronhuang@foxmail.com
 
发件人： staunchheart
发送时间： 2020-10-10 11:30
收件人： yaronzz/AIGCJson
抄送： Subscribed
主题： [yaronzz/AIGCJson] 如何处理list<T>呢？ (#1)
比如
class Student{
....
}
class xxx{
public:
string name;
list students;
}
这种情况如何处理呢？

**Comment by yaronzz** [comment]
正常了



yaronhuang@foxmail.com
 
发件人： staunchheart
发送时间： 2020-10-10 11:38
收件人： yaronzz/AIGCJson
抄送： Subscribed
主题： Re: [yaronzz/AIGCJson] 如何处理list<T>呢？ (#1)
我测试报这个错误
no match for 'operator[]' (operand types are 'std::__cxx11::list' and 'int')

**Comment by staunchheart** [comment]
封装得很优美，
非常感谢！

**Comment by yaronzz** [comment]
不客气
如果想支持其他类型，可以在AIGCJson.hpp中添加两条函数，模板可以看第60行、和第185行。
欢迎pull request


yaronhuang@foxmail.com
 
发件人： staunchheart
发送时间： 2020-10-10 13:49
收件人： yaronzz/AIGCJson
抄送： Yaronzz; State change
主题： Re: [yaronzz/AIGCJson] 如何处理list<T>呢？ (#1)
封装得很优美，
非常感谢！
