### ISSUE TITLE
如果类有多层呢？比如Student继承自Popole,

### ISSUE THREAD

**Issue by staunchheart** [yaronzz/AIGCJson#2]
我想用多层的类进行JSON反序列化。
如下
class Popole:PoBase
{
public:
    string name;
    int age;

    AIGC_JSON_HELPER(name, age)//成员注册
};
class Student:Popole{
public:
	 string depart;
	 int grade;
	 AIGC_JSON_HELPER(depart, grade)//成员注册
};
class Class:PoBase{
public:
    string name;
    list\<Student\> students;
    Popole master;
    AIGC_JSON_HELPER(name, students,master)//成员注册

};

{\"name\":\"小一班\",\"master\":{\"name\":\"刘老师\",\"age\":35},\"student\":[{\"name\":\"张小明\",\"age\":5,\"grade\":3,\"depart\":\"小学\"},{\"name\":\"张小红\",\"age\":7,\"grade\":3,\"depart\":\"小学\"}]}

这样的JSON解析不了students
有没有办法解决这类需求呢？

**Comment by yaronzz** [comment]
什么意思？student的基类people没有赋值？




yaronhuang@foxmail.com
 
发件人： staunchheart
发送时间： 2020-10-21 14:51
收件人： yaronzz/AIGCJson
抄送： Subscribed
主题： [yaronzz/AIGCJson] 如果类有多层呢？比如Student继也没有自Popole, (#2)
我想用多层的类进行JSON反序列化。
如下
class Popole:PoBase
{
public:
string name;
int age;
AIGC_JSON_HELPER(name, age)//成员注册

};
class Student:Popole{
public:
string depart;
int grade;
AIGC_JSON_HELPER(depart, grade)//成员注册
};
class Class:PoBase{
public:
string name;
list students;
Popole master;
AIGC_JSON_HELPER(name, students,master)//成员注册
};
{"name":"小一班","master":{"name":"刘老师","age":35},"student":[{"name":"张小明","age":5,"grade":3,"depart":"小学"},{"name":"张小红","age":7,"grade":3,"depart":"小学"}]}
这样的JSON解析不了students
有没有办法解决这类需求呢？

**Comment by staunchheart** [comment]
反序列化的student的list 空的。
这里Popole有AIGC_JSON_HELPER
Student继承自Popole,也有AIGC_JSON_HELPER  重载了。

**Comment by staunchheart** [comment]
就是人有姓名和年龄。
学生，继承自人  多了学部与年级。

班级有
  名称
 班主任：人
   list<学生>

老大的这个要制不适合处理继承，并且父类与派生类都面要序列化字段的应用场景

**Comment by yaronzz** [comment]
你找个json字符串里面，"student"少加了个s吧



yaronhuang@foxmail.com
 
发件人： staunchheart
发送时间： 2020-10-21 17:14
收件人： yaronzz/AIGCJson
抄送： Yaronzz; Comment
主题： Re: [yaronzz/AIGCJson] 如果类有多层呢？比如Student继承自Popole, (#2)
反序列化的student的list 空的。
这里Popole有AIGC_JSON_HELPER
Student继承自Popole,也有AIGC_JSON_HELPER 重载了。

**Comment by yaronzz** [comment]
这个可以用基类指针来实现，就是估计要加多一条声明语句



yaronhuang@foxmail.com
 
发件人： staunchheart
发送时间： 2020-10-21 17:18
收件人： yaronzz/AIGCJson
抄送： Yaronzz; Comment
主题： Re: [yaronzz/AIGCJson] 如果类有多层呢？比如Student继承自Popole, (#2)
就是人有姓名和年龄。
学生，继承自人 多了学部与年级。
班级有
名称
班主任：人
list<学生>
老大的这个要制不适合处理继承，并且父类与派生类都面要序列化字段的应用场景

**Comment by yaronzz** [comment]
可以了
```cpp
class Popole 
{
public:
    string name;
    int age;

    AIGC_JSON_HELPER(name, age) //成员注册
};
class Student : Popole
{
public:
    string depart;
    int grade;
    AIGC_JSON_HELPER(depart, grade) //成员注册
    AIGC_JSON_HELPER_BASE((Popole*)this) //基类注册
};
class Class 
{
public:
    string name;
    std::list<Student> students;
    Popole master;
    AIGC_JSON_HELPER(name, students, master) //成员注册
};

string sjson = R"({
    "name" : "小一班", "master" : {"name" : "刘老师", "age" : 35}, "students" : [ {"name" : "张小明", "age" : 5, "grade" : 3, "depart" : "小学"}, {"name" : "张小红", "age" : 7, "grade" : 3, "depart" : "小学"} ]
})";

int main()
{
    Class my;
    JsonHelper::JsonToObject(my, sjson);
    return 0;
}
```

**Comment by staunchheart** [comment]
good job.
TKS,前面的students是我的失误，惭愧。我当时重点在看哪个派生类覆盖了基类的方法了，老大的这个方式非常的棒，一如继往的优美。。
