### ISSUE TITLE
请教大佬，如果是想在成员中使用数组，该如何实现？

### ISSUE THREAD

**Issue by Mafuyu** [yaronzz/AIGCJson#3]
比如这样：
```C++
class Student {
public:
    string Name[2];
    int Age[2];

    AIGC_JSON_HELPER(Name, Age)
};
```

**Comment by yaronzz** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    




指针与原生数组由于空间分配和长度的问题会让设计变得无比复杂，比如char name[20]，所以不支持这种类型。数组统一使用std::vector<类型>
    
    Best regards!—————————————————YaornzzEmail: yaronhuang@foxmail.comWeb: https://yaronzz.topGithub :https://github.com/yaronzz
    
    
    

    




    在2021年3月5日 11:20，Mafuyu<notifications@github.com> 写道： 




比如这样：

class Student {

public:

    string Name[2];

    int Age[2];



    AIGC_JSON_HELPER(Name, Age)

};

**Comment by Mafuyu** [comment]
感谢回复。还有个问题想请教，如果要用其他整数类型，如int8_t或者uint16_t，该怎么办呢？

**Comment by yaronzz** [comment]
可以自己加一些新的类型接口，在readme最后一章有讲，不然的话就直接用int，short之类

Yaron
