### ISSUE TITLE
error: expected nested-name-specifier before numeric constant

### ISSUE THREAD

**Issue by dreamyouonly** [yaronzz/AIGCJson#4]
I am  trying to use your project for my task.
However , the compiler told me some errors.
I am not sure if the environment led to this problem.

here are the reports.
> ../src/internet/model/include/rapidjson/internal/meta.h:107: error: expected nested-name-specifier before numeric constant
../src/internet/model/include/rapidjson/internal/meta.h:107: error: expected ‘>’ before numeric constant
../src/internet/model/include/rapidjson/internal/meta.h:109: error: ‘D’ was not declared in this scope
../src/internet/model/include/rapidjson/internal/meta.h:109: error: template argument 1 is invalid
../src/internet/model/include/rapidjson/internal/meta.h:115: error: ISO C++ forbids declaration of ‘D’ with no type
../src/internet/model/include/rapidjson/internal/meta.h:115: error: expected ‘,’ or ‘...’ before ‘*’ token
../src/internet/model/include/rapidjson/internal/meta.h:116: error: ISO C++ forbids declaration of ‘parameter’ with no type
../src/internet/model/include/rapidjson/internal/meta.h:116: error: expected ‘,’ or ‘...’ before numeric constant
../src/internet/model/include/rapidjson/internal/meta.h:119: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/internet/model/include/rapidjson/internal/meta.h:119: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/internet/model/include/rapidjson/internal/meta.h:119: error: declaration of ‘operator const int’ as non-function
../src/internet/model/include/rapidjson/internal/meta.h:119: error: expected ‘;’ before numeric constant
../src/internet/model/include/rapidjson/internal/meta.h:120: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/internet/model/include/rapidjson/internal/meta.h:120: error: ‘operator const int’ does not name a type
../src/internet/model/include/rapidjson/internal/meta.h:126: error: expected nested-name-specifier before numeric constant
../src/internet/model/include/rapidjson/internal/meta.h:126: error: expected ‘>’ before numeric constant
../src/internet/model/include/rapidjson/internal/meta.h:127: error: ‘D’ was not declared in this scope
../src/internet/model/include/rapidjson/internal/meta.h:127: error: type/value mismatch at argument 1 in template parameter list for ‘template<class T, class U> struct rapidjson::internal::IsSame’
../src/internet/model/include/rapidjson/internal/meta.h:127: error:   expected a type, got ‘2’
../src/internet/model/include/rapidjson/internal/meta.h:127: error: template argument 2 is invalid
../src/internet/model/include/rapidjson/internal/meta.h:127: error: ‘D’ was not declared in this scope
../src/internet/model/include/rapidjson/internal/meta.h:127: error: wrong number of template arguments (2, should be 1)
../src/internet/model/include/rapidjson/internal/meta.h:107: error: provided for ‘template<int <anonymous> > struct rapidjson::internal::IsBaseOfImpl’
../src/internet/model/include/rapidjson/internal/meta.h:127: error: template argument 1 is invalid
../src/internet/model/include/rapidjson/internal/meta.h:127: error: template argument 1 is invalid
../src/internet/model/include/rapidjson/internal/meta.h:127: error: template argument 2 is invalid
../src/internet/model/include/rapidjson/internal/meta.h:127: error: expected ‘{’ before ‘Type’
../src/internet/model/include/rapidjson/internal/meta.h:127: error: invalid type in declaration before ‘{’ token
../src/internet/model/include/rapidjson/internal/meta.h:127: error: template declaration of ‘int rapidjson::internal::Type’
In file included from ../src/internet/model/include/AIGCJson.hpp:27,
                 from ../src/internet/model/mp-tcp-socket-base.cc:30:
../src/internet/model/include/rapidjson/document.h:495: error: wrong number of template arguments (2, should be 1)
../src/internet/model/include/rapidjson/internal/meta.h:126: error: provided for ‘template<int <anonymous> > struct rapidjson::internal::IsBaseOf’
../src/internet/model/include/rapidjson/document.h:495: error: expected ‘{’ before ‘Type’
../src/internet/model/include/rapidjson/document.h:495: error: invalid type in declaration before ‘{’ token
../src/internet/model/include/rapidjson/document.h:495: error: template declaration of ‘int rapidjson::internal::Type’
../src/internet/model/include/rapidjson/document.h: In instantiation of ‘rapidjson::internal::IsGenericValue<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > >’:
../src/internet/model/include/rapidjson/internal/meta.h:69:   instantiated from ‘rapidjson::internal::OrExpr<rapidjson::internal::IsPointer<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > >, rapidjson::internal::IsGenericValue<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > > >’
../src/internet/model/include/rapidjson/internal/meta.h:145:   instantiated from ‘rapidjson::internal::DisableIf<rapidjson::internal::OrExpr<rapidjson::internal::IsPointer<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > >, rapidjson::internal::IsGenericValue<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > > >, rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >&>’
../src/internet/model/include/AIGCJson.hpp:431:   instantiated from here
../src/internet/model/include/rapidjson/document.h:498: error: invalid use of incomplete type ‘struct rapidjson::internal::IsGenericValueImpl<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >, void, void>’
../src/internet/model/include/rapidjson/document.h:491: error: declaration of ‘struct rapidjson::internal::IsGenericValueImpl<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >, void, void>’
In file included from ../src/internet/model/include/rapidjson/reader.h:24,
                 from ../src/internet/model/include/rapidjson/document.h:20,
                 from ../src/internet/model/include/AIGCJson.hpp:27,
                 from ../src/internet/model/mp-tcp-socket-base.cc:30:
../src/internet/model/include/rapidjson/internal/meta.h: In instantiation of ‘rapidjson::internal::OrExpr<rapidjson::internal::IsPointer<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > >, rapidjson::internal::IsGenericValue<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > > >’:
../src/internet/model/include/rapidjson/internal/meta.h:145:   instantiated from ‘rapidjson::internal::DisableIf<rapidjson::internal::OrExpr<rapidjson::internal::IsPointer<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > >, rapidjson::internal::IsGenericValue<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > > >, rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >&>’
../src/internet/model/include/AIGCJson.hpp:431:   instantiated from here
../src/internet/model/include/rapidjson/internal/meta.h:69: error: ‘Value’ is not a member of ‘rapidjson::internal::IsGenericValue<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > >’
../src/internet/model/include/rapidjson/internal/meta.h: In instantiation of ‘rapidjson::internal::DisableIf<rapidjson::internal::OrExpr<rapidjson::internal::IsPointer<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > >, rapidjson::internal::IsGenericValue<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > > >, rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >&>’:
../src/internet/model/include/AIGCJson.hpp:431:   instantiated from here
../src/internet/model/include/rapidjson/internal/meta.h:145: error: ‘Value’ is not a member of ‘rapidjson::internal::OrExpr<rapidjson::internal::IsPointer<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > >, rapidjson::internal::IsGenericValue<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > > >’
In file included from ../src/internet/model/mp-tcp-socket-base.cc:30:
../src/internet/model/include/AIGCJson.hpp:768: error: expected primary-expression before ‘{’ token
../src/internet/model/include/AIGCJson.hpp:818: error: expected primary-expression before ‘{’ token
Waf: Leaving directory `/home/wjt/eclipse/work-space/finalbs/build'
Build failed
 -> task in 'ns3-internet' failed (exit status 1): 
	{task 140218702466000: cxx mp-tcp-socket-base.cc -> mp-tcp-socket-base.cc.1.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-std=c++0x', '-Wno-error=deprecated-declarations', '-std=c++0x', '-fstrict-aliasing', '-std=c++0x', '-Wstrict-aliasing', '-fPIC', '-pthread', '-I.', '-I..', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_IF_TUN_H=1', '../src/internet/model/mp-tcp-socket-base.cc', '-c', '-o', 'src/internet/model/mp-tcp-socket-base.cc.1.o']
"/home/wjt/eclipse/work-space/finalbs/waf build" terminated with exit code 1. Build might be incomplete.

here are the screenshots.
![image](https://user-images.githubusercontent.com/51074339/114721395-77172880-9d6b-11eb-9d3f-570747546f57.png)

![image](https://user-images.githubusercontent.com/51074339/114721543-99a94180-9d6b-11eb-96a7-5022cde7b86f.png)

It's extremely possible that my environment is different with you. 
My Environment is gcc/g++ 4.4.7, and the command has added the attribute "-std=c++0x"
Could you please help me? Thanks a lot.
应用场景是使用waf编译工具做ns3项目的二次开发

**Comment by yaronzz** [comment]
-std=c++11

**Comment by dreamyouonly** [comment]
> -std=c++11

-std=c++11 is helpful. Thanks a lot .
